import { SimulationPayload, CURRENT_SCHEMA_VERSION } from '../migrations/migrationRunner';

export const TEMPLATES: Record<string, Partial<SimulationPayload>> = {
  'two-sum': {
    name: 'Two Sum (Two Pointers / Pair Search)',
    description: 'Dry run finding two numbers in [2, 7, 11, 15] that add up to target = 9.',
    schemaVersion: CURRENT_SCHEMA_VERSION,
    settings: {
      canvasWidth: 6000,
      canvasHeight: 4000,
      gridSize: 20,
      snapToGrid: true,
      theme: 'dark',
      defaultPlaybackSpeed: 1.0,
    },
    steps: [
      {
        id: 'step_1',
        name: 'Step 1: Initialize Pointers & Target',
        description: 'Initialize array [2, 7, 11, 15] with pointer i at index 0 and pointer j at index 1.',
        durationMs: 900,
        objects: [
          {
            id: 'array_nums',
            type: 'array',
            x: 280,
            y: 220,
            width: 320,
            height: 80,
            zIndex: 5,
            style: {
              backgroundColor: '#1e293b',
              borderColor: '#38bdf8',
              borderWidth: 2,
              borderRadius: 12,
              color: '#f8fafc',
              fontSize: 18,
            },
            data: {
              name: 'nums',
              showIndexes: true,
              orientation: 'horizontal',
              cellSize: 70,
              elements: [
                { id: 'cell_0', value: 2, highlight: 'active' },
                { id: 'cell_1', value: 7, highlight: 'active' },
                { id: 'cell_2', value: 11, highlight: 'none' },
                { id: 'cell_3', value: 15, highlight: 'none' },
              ],
            },
          },
          {
            id: 'pointer_i',
            type: 'pointer',
            x: 295,
            y: 120,
            width: 40,
            height: 60,
            zIndex: 15,
            style: { color: '#38bdf8' },
            data: {
              label: 'i',
              direction: 'down',
              color: '#38bdf8',
              targetNodeId: 'array_nums',
              targetIndex: 0,
            },
          },
          {
            id: 'pointer_j',
            type: 'pointer',
            x: 365,
            y: 350,
            width: 40,
            height: 60,
            zIndex: 15,
            style: { color: '#f43f5e' },
            data: {
              label: 'j',
              direction: 'up',
              color: '#f43f5e',
              targetNodeId: 'array_nums',
              targetIndex: 1,
            },
          },
          {
            id: 'var_target',
            type: 'variable',
            x: 280,
            y: 450,
            width: 140,
            height: 56,
            zIndex: 10,
            style: {
              backgroundColor: '#1e1b4b',
              borderColor: '#818cf8',
              borderWidth: 1,
              borderRadius: 8,
              color: '#c7d2fe',
              fontSize: 16,
            },
            data: {
              name: 'target',
              value: 9,
              dataType: 'number',
              animationStyle: 'strikethrough',
            },
          },
          {
            id: 'var_sum',
            type: 'variable',
            x: 450,
            y: 450,
            width: 150,
            height: 56,
            zIndex: 10,
            style: {
              backgroundColor: '#064e3b',
              borderColor: '#34d399',
              borderWidth: 2,
              borderRadius: 8,
              color: '#a7f3d0',
              fontSize: 16,
            },
            data: {
              name: 'sum',
              value: 9,
              dataType: 'number',
              animationStyle: 'strikethrough',
            },
          },
          {
            id: 'text_note',
            type: 'text',
            x: 280,
            y: 530,
            width: 380,
            height: 48,
            zIndex: 2,
            style: {
              backgroundColor: 'rgba(15, 23, 42, 0.7)',
              borderColor: '#334155',
              borderWidth: 1,
              borderRadius: 8,
              color: '#34d399',
              fontSize: 15,
            },
            data: {
              text: 'nums[0] + nums[1] = 2 + 7 = 9 (Match found!)',
              fontSize: 15,
              fontWeight: 'bold',
              isCallout: true,
              badgeText: 'RESULT',
            },
          },
        ],
      },
      {
        id: 'step_2',
        name: 'Step 2: Checking next iteration example',
        description: 'Demonstrating moving pointer j to index 2 and calculating sum = 2 + 11 = 13.',
        durationMs: 900,
        objects: [
          {
            id: 'array_nums',
            type: 'array',
            x: 280,
            y: 220,
            width: 320,
            height: 80,
            zIndex: 5,
            style: {
              backgroundColor: '#1e293b',
              borderColor: '#38bdf8',
              borderWidth: 2,
              borderRadius: 12,
              color: '#f8fafc',
              fontSize: 18,
            },
            data: {
              name: 'nums',
              showIndexes: true,
              orientation: 'horizontal',
              cellSize: 70,
              elements: [
                { id: 'cell_0', value: 2, highlight: 'active' },
                { id: 'cell_1', value: 7, highlight: 'none' },
                { id: 'cell_2', value: 11, highlight: 'active' },
                { id: 'cell_3', value: 15, highlight: 'none' },
              ],
            },
          },
          {
            id: 'pointer_i',
            type: 'pointer',
            x: 295,
            y: 120,
            width: 40,
            height: 60,
            zIndex: 15,
            style: { color: '#38bdf8' },
            data: {
              label: 'i',
              direction: 'down',
              color: '#38bdf8',
              targetNodeId: 'array_nums',
              targetIndex: 0,
            },
          },
          {
            id: 'pointer_j',
            type: 'pointer',
            x: 435,
            y: 350,
            width: 40,
            height: 60,
            zIndex: 15,
            style: { color: '#f43f5e' },
            data: {
              label: 'j',
              direction: 'up',
              color: '#f43f5e',
              targetNodeId: 'array_nums',
              targetIndex: 2,
            },
          },
          {
            id: 'var_target',
            type: 'variable',
            x: 280,
            y: 450,
            width: 140,
            height: 56,
            zIndex: 10,
            style: {
              backgroundColor: '#1e1b4b',
              borderColor: '#818cf8',
              borderWidth: 1,
              borderRadius: 8,
              color: '#c7d2fe',
              fontSize: 16,
            },
            data: {
              name: 'target',
              value: 9,
              dataType: 'number',
              animationStyle: 'strikethrough',
            },
          },
          {
            id: 'var_sum',
            type: 'variable',
            x: 450,
            y: 450,
            width: 150,
            height: 56,
            zIndex: 10,
            style: {
              backgroundColor: '#451a03',
              borderColor: '#f59e0b',
              borderWidth: 2,
              borderRadius: 8,
              color: '#fde68a',
              fontSize: 16,
            },
            data: {
              name: 'sum',
              value: 13,
              dataType: 'number',
              animationStyle: 'strikethrough',
            },
          },
          {
            id: 'text_note',
            type: 'text',
            x: 280,
            y: 530,
            width: 380,
            height: 48,
            zIndex: 2,
            style: {
              backgroundColor: 'rgba(15, 23, 42, 0.7)',
              borderColor: '#334155',
              borderWidth: 1,
              borderRadius: 8,
              color: '#fbbf24',
              fontSize: 15,
            },
            data: {
              text: 'nums[0] + nums[2] = 2 + 11 = 13 (sum > target)',
              fontSize: 15,
              fontWeight: 'bold',
              isCallout: true,
              badgeText: 'CHECK',
            },
          },
        ],
      },
      {
        id: 'step_3',
        name: 'Step 3: Move Pointer i to 1 and j to 2',
        description: 'Testing next candidate pair nums[1] + nums[2] = 7 + 11 = 18.',
        durationMs: 900,
        objects: [
          {
            id: 'array_nums',
            type: 'array',
            x: 280,
            y: 220,
            width: 320,
            height: 80,
            zIndex: 5,
            style: {
              backgroundColor: '#1e293b',
              borderColor: '#38bdf8',
              borderWidth: 2,
              borderRadius: 12,
              color: '#f8fafc',
              fontSize: 18,
            },
            data: {
              name: 'nums',
              showIndexes: true,
              orientation: 'horizontal',
              cellSize: 70,
              elements: [
                { id: 'cell_0', value: 2, highlight: 'none' },
                { id: 'cell_1', value: 7, highlight: 'active' },
                { id: 'cell_2', value: 11, highlight: 'active' },
                { id: 'cell_3', value: 15, highlight: 'none' },
              ],
            },
          },
          {
            id: 'pointer_i',
            type: 'pointer',
            x: 365,
            y: 120,
            width: 40,
            height: 60,
            zIndex: 15,
            style: { color: '#38bdf8' },
            data: {
              label: 'i',
              direction: 'down',
              color: '#38bdf8',
              targetNodeId: 'array_nums',
              targetIndex: 1,
            },
          },
          {
            id: 'pointer_j',
            type: 'pointer',
            x: 435,
            y: 350,
            width: 40,
            height: 60,
            zIndex: 15,
            style: { color: '#f43f5e' },
            data: {
              label: 'j',
              direction: 'up',
              color: '#f43f5e',
              targetNodeId: 'array_nums',
              targetIndex: 2,
            },
          },
          {
            id: 'var_target',
            type: 'variable',
            x: 280,
            y: 450,
            width: 140,
            height: 56,
            zIndex: 10,
            style: {
              backgroundColor: '#1e1b4b',
              borderColor: '#818cf8',
              borderWidth: 1,
              borderRadius: 8,
              color: '#c7d2fe',
              fontSize: 16,
            },
            data: {
              name: 'target',
              value: 9,
              dataType: 'number',
              animationStyle: 'strikethrough',
            },
          },
          {
            id: 'var_sum',
            type: 'variable',
            x: 450,
            y: 450,
            width: 150,
            height: 56,
            zIndex: 10,
            style: {
              backgroundColor: '#4c0519',
              borderColor: '#f43f5e',
              borderWidth: 2,
              borderRadius: 8,
              color: '#fecdd3',
              fontSize: 16,
            },
            data: {
              name: 'sum',
              value: 18,
              dataType: 'number',
              animationStyle: 'strikethrough',
            },
          },
          {
            id: 'text_note',
            type: 'text',
            x: 280,
            y: 530,
            width: 380,
            height: 48,
            zIndex: 2,
            style: {
              backgroundColor: 'rgba(15, 23, 42, 0.7)',
              borderColor: '#334155',
              borderWidth: 1,
              borderRadius: 8,
              color: '#f87171',
              fontSize: 15,
            },
            data: {
              text: 'nums[1] + nums[2] = 7 + 11 = 18',
              fontSize: 15,
              fontWeight: 'bold',
              isCallout: true,
              badgeText: 'EVAL',
            },
          },
        ],
      },
    ],
  },
  'binary-search': {
    name: 'Binary Search (Find target = 7)',
    description: 'Step-by-step interval halving with low, mid, and high pointers.',
    schemaVersion: CURRENT_SCHEMA_VERSION,
    settings: {
      canvasWidth: 6000,
      canvasHeight: 4000,
      gridSize: 20,
      snapToGrid: true,
      theme: 'dark',
      defaultPlaybackSpeed: 1.0,
    },
    steps: [
      {
        id: 'bs_step_1',
        name: 'Step 1: low = 0, high = 6, mid = 3',
        description: 'Calculate mid = (0 + 6) / 2 = 3. Compare nums[3] = 9 with target 7.',
        durationMs: 900,
        objects: [
          {
            id: 'bs_arr',
            type: 'array',
            x: 180,
            y: 220,
            width: 500,
            height: 80,
            zIndex: 5,
            style: {
              backgroundColor: '#1e293b',
              borderColor: '#38bdf8',
              borderWidth: 2,
              borderRadius: 12,
              color: '#f8fafc',
              fontSize: 18,
            },
            data: {
              name: 'arr',
              showIndexes: true,
              orientation: 'horizontal',
              cellSize: 65,
              elements: [
                { id: 'c0', value: 1, highlight: 'none' },
                { id: 'c1', value: 3, highlight: 'none' },
                { id: 'c2', value: 5, highlight: 'none' },
                { id: 'c3', value: 9, highlight: 'active' },
                { id: 'c4', value: 12, highlight: 'none' },
                { id: 'c5', value: 15, highlight: 'none' },
                { id: 'c6', value: 20, highlight: 'none' },
              ],
            },
          },
          {
            id: 'ptr_low',
            type: 'pointer',
            x: 195,
            y: 120,
            width: 40,
            height: 60,
            zIndex: 15,
            style: { color: '#38bdf8' },
            data: { label: 'low', direction: 'down', color: '#38bdf8', targetNodeId: 'bs_arr', targetIndex: 0 },
          },
          {
            id: 'ptr_mid',
            type: 'pointer',
            x: 390,
            y: 120,
            width: 40,
            height: 60,
            zIndex: 15,
            style: { color: '#fbbf24' },
            data: { label: 'mid', direction: 'down', color: '#fbbf24', targetNodeId: 'bs_arr', targetIndex: 3 },
          },
          {
            id: 'ptr_high',
            type: 'pointer',
            x: 585,
            y: 120,
            width: 40,
            height: 60,
            zIndex: 15,
            style: { color: '#f43f5e' },
            data: { label: 'high', direction: 'down', color: '#f43f5e', targetNodeId: 'bs_arr', targetIndex: 6 },
          },
          {
            id: 'var_mid_val',
            type: 'variable',
            x: 180,
            y: 430,
            width: 170,
            height: 56,
            zIndex: 10,
            style: { backgroundColor: '#1e293b', borderColor: '#64748b', borderWidth: 1, borderRadius: 8, color: '#e2e8f0', fontSize: 16 },
            data: { name: 'nums[mid]', value: 9, dataType: 'number', animationStyle: 'strikethrough' },
          },
          {
            id: 'var_target_bs',
            type: 'variable',
            x: 370,
            y: 430,
            width: 150,
            height: 56,
            zIndex: 10,
            style: { backgroundColor: '#1e1b4b', borderColor: '#818cf8', borderWidth: 1, borderRadius: 8, color: '#c7d2fe', fontSize: 16 },
            data: { name: 'target', value: 7, dataType: 'number', animationStyle: 'strikethrough' },
          },
          {
            id: 'text_bs_note',
            type: 'text',
            x: 180,
            y: 510,
            width: 450,
            height: 48,
            zIndex: 2,
            style: { backgroundColor: 'rgba(15, 23, 42, 0.7)', borderColor: '#334155', borderWidth: 1, borderRadius: 8, color: '#f59e0b', fontSize: 15 },
            data: { text: 'nums[mid] = 9 > target 7 → Search left half (high = mid - 1)', fontSize: 15, fontWeight: 'bold', isCallout: true, badgeText: 'COMPARE' },
          },
        ],
      },
      {
        id: 'bs_step_2',
        name: 'Step 2: low = 0, high = 2, mid = 1',
        description: 'Sub-array [1, 3, 5]. mid = 1 (value 3).',
        durationMs: 900,
        objects: [
          {
            id: 'bs_arr',
            type: 'array',
            x: 180,
            y: 220,
            width: 500,
            height: 80,
            zIndex: 5,
            style: {
              backgroundColor: '#1e293b',
              borderColor: '#38bdf8',
              borderWidth: 2,
              borderRadius: 12,
              color: '#f8fafc',
              fontSize: 18,
            },
            data: {
              name: 'arr',
              showIndexes: true,
              orientation: 'horizontal',
              cellSize: 65,
              elements: [
                { id: 'c0', value: 1, highlight: 'none' },
                { id: 'c1', value: 3, highlight: 'active' },
                { id: 'c2', value: 5, highlight: 'none' },
                { id: 'c3', value: 9, highlight: 'dimmed' },
                { id: 'c4', value: 12, highlight: 'dimmed' },
                { id: 'c5', value: 15, highlight: 'dimmed' },
                { id: 'c6', value: 20, highlight: 'dimmed' },
              ],
            },
          },
          {
            id: 'ptr_low',
            type: 'pointer',
            x: 195,
            y: 120,
            width: 40,
            height: 60,
            zIndex: 15,
            style: { color: '#38bdf8' },
            data: { label: 'low', direction: 'down', color: '#38bdf8', targetNodeId: 'bs_arr', targetIndex: 0 },
          },
          {
            id: 'ptr_mid',
            type: 'pointer',
            x: 260,
            y: 120,
            width: 40,
            height: 60,
            zIndex: 15,
            style: { color: '#fbbf24' },
            data: { label: 'mid', direction: 'down', color: '#fbbf24', targetNodeId: 'bs_arr', targetIndex: 1 },
          },
          {
            id: 'ptr_high',
            type: 'pointer',
            x: 325,
            y: 120,
            width: 40,
            height: 60,
            zIndex: 15,
            style: { color: '#f43f5e' },
            data: { label: 'high', direction: 'down', color: '#f43f5e', targetNodeId: 'bs_arr', targetIndex: 2 },
          },
          {
            id: 'var_mid_val',
            type: 'variable',
            x: 180,
            y: 430,
            width: 170,
            height: 56,
            zIndex: 10,
            style: { backgroundColor: '#1e293b', borderColor: '#64748b', borderWidth: 1, borderRadius: 8, color: '#e2e8f0', fontSize: 16 },
            data: { name: 'nums[mid]', value: 3, dataType: 'number', animationStyle: 'strikethrough' },
          },
          {
            id: 'var_target_bs',
            type: 'variable',
            x: 370,
            y: 430,
            width: 150,
            height: 56,
            zIndex: 10,
            style: { backgroundColor: '#1e1b4b', borderColor: '#818cf8', borderWidth: 1, borderRadius: 8, color: '#c7d2fe', fontSize: 16 },
            data: { name: 'target', value: 7, dataType: 'number', animationStyle: 'strikethrough' },
          },
          {
            id: 'text_bs_note',
            type: 'text',
            x: 180,
            y: 510,
            width: 450,
            height: 48,
            zIndex: 2,
            style: { backgroundColor: 'rgba(15, 23, 42, 0.7)', borderColor: '#334155', borderWidth: 1, borderRadius: 8, color: '#38bdf8', fontSize: 15 },
            data: { text: 'nums[mid] = 3 < target 7 → Search right half (low = mid + 1)', fontSize: 15, fontWeight: 'bold', isCallout: true, badgeText: 'HALVE' },
          },
        ],
      },
    ],
  },
};
